package ExceptionHandling;

public class TryCatchFinally {

	public static void main(String[] args) {
		try {
			int i=5/2;
		}
		catch(ArithmeticException ae) {
			System.out.println("Exception caught.");
		}
		finally {
			System.out.println("Finally case is caught.");
		}
	}

}
